Tugas SIOT Fork Calvin X SIJA
Siotics/led-git-exec pull request #14
Opened 2023-10-21 07:42 UTC by Zepicxs

2023-10-21 11:49 UTC, SyaddadRaihanPutra commented on initiates/Calvin_XSIJA_IfStatement.ino
Please correct the code again, there is still something wrong. The code doesn't run well 🔥

2023-10-21 11:55 UTC, SyaddadRaihanPutra requested changes
Please correct the code again, there is still something wrong. The code doesn't run well 🔥

2023-10-22 07:07 UTC, closed without merging

2023-10-22 23:38 UTC, Zepicxs commented
> Please correct the code again, there is still something wrong. The code doesn't run well 🔥

Okeh

2023-10-23 03:01 UTC, Zepicxs commented
Where is the error sir? i didnt found any error in my tinker cad and it works properly. smh💀

2023-10-23 04:27 UTC, SyaddadRaihanPutra reviewed
Sudah saya cek masih ada kesalahan pada percabangan kondisi nya, saya menguji dengan Wokwi dan TinkerCad

2023-10-25 04:26 UTC, Zepicxs commented
> Sudah saya cek masih ada kesalahan pada percabangan kondisi nya, saya menguji dengan Wokwi dan TinkerCad

okey akan saya cek lagi